# Maxwell MySQL to Kafka Configurations
producer=kafka
kafka.bootstrap.servers=master:9092
kafka_topic=ods_mall_data

host=master
user=root
password=123456
jdbc_options=useSSL=false&serverTimezone=UTC

# Filter to include only specific database and tables
filter=include:ds_db01.*
